insert into tblcompound (Compound) values('Altura Bata');
insert into tblcompound (Compound) values('Altura Matanda');
insert into tblcompound (Compound) values('Altura-South');
insert into tblcompound (Compound) values('Ambulong');
insert into tblcompound (Compound) values('Bañadero');
insert into tblcompound (Compound) values('Bagbag');
insert into tblcompound (Compound) values('Bagumbayan');
insert into tblcompound (Compound) values('Balele');
insert into tblcompound (Compound) values('Banjo East (Bungkalot)');
insert into tblcompound (Compound) values('Banjo West (Banjo Laurel)');
insert into tblcompound (Compound) values('Bilog-bilog');
insert into tblcompound (Compound) values('Boot');
insert into tblcompound (Compound) values('Cale');
insert into tblcompound (Compound) values('Darasa');
insert into tblcompound (Compound) values('Gonzales');
insert into tblcompound (Compound) values('Hidalgo');
insert into tblcompound (Compound) values('Janopol');
insert into tblcompound (Compound) values('Janopol Oriental');
insert into tblcompound (Compound) values('Laurel');
insert into tblcompound (Compound) values('Luyos');
insert into tblcompound (Compound) values('Mabini');
insert into tblcompound (Compound) values('Malaking Pulo');
insert into tblcompound (Compound) values('Maria Paz');
insert into tblcompound (Compound) values('Maugat');
insert into tblcompound (Compound) values('Montaña (Ik-ik)');
insert into tblcompound (Compound) values('Natatas');
insert into tblcompound (Compound) values('Pagaspas (Balokbalok)');
insert into tblcompound (Compound) values('Pantay Matanda');
insert into tblcompound (Compound) values('Pantay Bata');
insert into tblcompound (Compound) values('Poblacion Barangay 1');
insert into tblcompound (Compound) values('Poblacion Barangay 2');
insert into tblcompound (Compound) values('Poblacion Barangay 3');
insert into tblcompound (Compound) values('Poblacion Barangay 4');
insert into tblcompound (Compound) values('Poblacion Barangay 5');
insert into tblcompound (Compound) values('Poblacion Barangay 6');
insert into tblcompound (Compound) values('Poblacion Barangay 7');
insert into tblcompound (Compound) values('Sala');
insert into tblcompound (Compound) values('Sambat');
insert into tblcompound (Compound) values('San Jose');
insert into tblcompound (Compound) values('Santol (Doña Jacoba Garcia)');
insert into tblcompound (Compound) values('Santor');
insert into tblcompound (Compound) values('Sulpoc');
insert into tblcompound (Compound) values('Suplang');
insert into tblcompound (Compound) values('Talaga');
insert into tblcompound (Compound) values('Tinurik');
insert into tblcompound (Compound) values('Trapiche');
insert into tblcompound (Compound) values('Ulango');
insert into tblcompound (Compound) values('Wawa');
